### ISSUE TITLE
开启插件后，图片报错401

### ISSUE THREAD

**Issue by VellowChire** [guqing/plugin-cloudinary#10]
出现问题的站点 [https://www.vellow.fun/archives/bf0d9947-2374-4d35-88d5-24df180070bb](https://www.vellow.fun/archives/bf0d9947-2374-4d35-88d5-24df180070bb)
X-Cld-Error: Images of type fetch are restricted in this account

萌新站长一位 如果问出的是铸币问题请见谅🥲
![屏幕截图 2024-06-25 233318](https://github.com/guqing/plugin-cloudinary/assets/144928681/dc9456f7-9390-4874-8fdd-a762a4c414e6)
![屏幕截图 2024-06-25 233218](https://github.com/guqing/plugin-cloudinary/assets/144928681/474c4930-ba68-4a89-bc6b-fa7a51384b54)
![屏幕截图 2024-06-25 235343](https://github.com/guqing/plugin-cloudinary/assets/144928681/58498b91-3d92-4d03-984a-f57c83335c03)

**Comment by guqing** [comment]
请在插件设置中检查一下你的配置是否正确

**Comment by VellowChire** [comment]
按照github页填的 应该没有问题
![smh_edit_1719406794453](https://github.com/guqing/plugin-cloudinary/assets/144928681/b62bf67d-2429-41f6-b5f3-1ad9fcb2fe0a)
![smh_edit_1719406750188](https://github.com/guqing/plugin-cloudinary/assets/144928681/cf9c83ac-1cfe-48ec-a108-dfe0b8804bbd)

**Comment by VellowChire** [comment]
谢谢大佬，已成功解决！
在尝试**生成新的APIKeys**以及在**Cloudinary安全设置项**中关闭下图中选项之后解决了问题
不知道是哪个操作起了作用🤔
![屏幕截图 2024-06-26 230739](https://github.com/guqing/plugin-cloudinary/assets/144928681/1d2b7740-d356-4a0f-987d-2639d7e79058)

**Comment by wenjing-xin** [comment]
请问最后是通过修改 Cloudinary 安全设置生效的吗。我现在也遇到了类似问题 一直 401

**Comment by VellowChire** [comment]
> 请问最后是通过修改 Cloudinary 安全设置生效的吗。我现在也遇到了类似问题 一直 401

更换新的api keys 或者尝试更改安全设置
因为当时我是两个一起改的 所以也不知道是哪个更改生效了
