### ISSUE TITLE
好像没效果

### ISSUE THREAD

**Issue by adozhao** [guqing/plugin-cloudinary#3]
缓存清除了，也正确配置了，包括无痕模式下，好像没起作用~

**Comment by guqing** [comment]
看浏览器控制台的 img 过滤是否将图片的 type 变为了 webp （background 设置的背景图除外）
<img width="506" alt="image" src="https://github.com/guqing/plugin-cloudinary/assets/38999863/fdad64b1-38a1-4c0a-82d6-d4fbf1e3d52e">
并且 img 标签多了 srcset 属性
<img width="601" alt="image" src="https://github.com/guqing/plugin-cloudinary/assets/38999863/8e80f40c-4a57-4aaa-a382-ab229cd338d6">

如果这些都没有，可以提供一下你正在使用的主题名或下载链接我试试

**Comment by guqing** [comment]
看了你主页的博客地址发现是生效的呢，不知道你说的没起作用是说的什么
<img width="1515" alt="image" src="https://github.com/guqing/plugin-cloudinary/assets/38999863/7ba591d8-c03d-4970-8552-705e67896053">

**Comment by adozhao** [comment]
昨天确实不行，突然就好了...
感谢大美女
![1D38F369](https://github.com/guqing/plugin-cloudinary/assets/23180747/dc514671-86b9-429e-a560-96da3feee253)

**Comment by guqing** [comment]
![image](https://github.com/guqing/plugin-cloudinary/assets/38999863/72953ff3-e605-42c1-a2ee-6af7b84c29b9)
