### ISSUE TITLE
卸载插件后在应用商店中提示版本不兼容

### ISSUE THREAD

**Issue by JeffreyZeng-dev** [guqing/plugin-cloudinary#4]
![image](https://github.com/guqing/plugin-cloudinary/assets/73866989/502b520b-25fe-4664-a576-c32217f3a7b7)
安装以后，进行卸载并删除配置，在应用商店中会显示版本不兼容！！！

**Comment by guqing** [comment]
刚刚重新发布了 1.0.1 版本你可以重新试试，今天白天的时候使用了新的 cd 配置来自动更新到应用市场但是发现有问题然后删除了，可能有缓存导致的

**Comment by JohnNiang** [comment]
Hi @UPToZ-Core , 新版已经发布，可以再试试：<https://www.halo.run/store/apps/app-mhQIV?tab=releases>。

**Comment by JeffreyZeng-dev** [comment]
> Hi @UPToZ-Core , 新版已经发布，可以再试试：https://www.halo.run/store/apps/app-mhQIV?tab=releases。

已经正常，感谢！
