### ISSUE TITLE
用了这个插件我博客媒体文件都不能加载，为啥，文本文件可以显示加载

### ISSUE THREAD

**Issue by pp6451303** [guqing/plugin-cloudinary#5]
用了这个插件我博客媒体文件都不能加载，为啥，文本文件可以显示加载

**Comment by guqing** [comment]
什么表现呢，你这么说我很难想象到🤔，比如浏览器网络请求是什么或者错误是什么，以便我排查为什么访问不到

**Comment by pp6451303** [comment]
有图片的位置会显示“cloudinary envoy 数字”。我是用群晖docker搭建的

---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年3月30日(周六) 凌晨0:34
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [guqing/plugin-cloudinary] 用了这个插件我博客媒体文件都不能加载，为啥，文本文件可以显示加载 (Issue #5)




 
什么表现呢，你这么说我很难想象到🤔，比如浏览器网络请求是什么或者错误是什么，以便我排查为什么访问不到

**Comment by guqing** [comment]
你使用的主题是什么呢，我尝试复线一下，我怀疑是此插件在某些主题下会不正确的处理图片导致的，目前没有想到一个完美的方案来处理 html，jsoup 会改变主题的 html 结构并且在有些主题下会得到错误的html结构因此我没有使用 jsoup 而是手写的，或许出现了意外

**Comment by pp6451303** [comment]
主题是：Sakura
2.1.0
按使用方法：输入Cloud Name&nbsp;*key等信息后由“cloudinary envoy 数字”变为下图


即是加载失败


&nbsp;


…
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年3月30日(星期六) 凌晨0:49
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [guqing/plugin-cloudinary] 用了这个插件我博客媒体文件都不能加载，为啥，文本文件可以显示加载 (Issue #5)














 
你使用的主题是什么呢，我怀疑是此插件在某些主题下会不正确的处理图片导致的，目前没有想到一个完美的方案来处理 html，jsoup 会改变主题的 html 结构并且在有些主题下会得到错误的html结构因此我没有使用 jsoup 而是手写的，或许出现了意外

**Comment by guqing** [comment]
Hi @pp6451303 抱歉回复晚了，由于你的回复并无法看到图片，我使用 Sakura 了但没有复现问题，后续我会优化一下写法，以排除这种可能
