### ISSUE TITLE
提个建议，可以加入域名手动填写吗

### ISSUE THREAD

**Issue by hello-yunshu** [guqing/plugin-cloudinary#8]
用的时候发现，如果有反向代理的话，会出现这样：
`https://res.cloudinary.com/drrapv49j/image/fetch/c_limit,f_webp,q_70,w_1920/http://localhost:8090/upload......`
里面的`http://localhost`没法修改，图片就加载不出来😭

**Comment by guqing** [comment]
这个貌似和反向代理没有关系，检查一下 external-url 的配置是否正确
系统概览中的外部访问地址需要是域名，不能是 localhost，如果不正确参考文档修改
<img width="626" alt="image" src="https://github.com/guqing/plugin-cloudinary/assets/38999863/0dc82f14-fbe6-47a9-8e4d-9d65047fd6e1">

**Comment by hello-yunshu** [comment]
> 这个貌似和反向代理没有关系，检查一下 external-url 的配置是否正确 系统概览中的外部访问地址需要是域名，不能是 localhost，如果不正确参考文档修改 <img alt="image" width="626" src="https://private-user-images.githubusercontent.com/38999863/329212231-0dc82f14-fbe6-47a9-8e4d-9d65047fd6e1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUyODc4NjcsIm5iZiI6MTcxNTI4NzU2NywicGF0aCI6Ii8zODk5OTg2My8zMjkyMTIyMzEtMGRjODJmMTQtZmJlNi00N2E5LThlNGQtOWQ2NTA0N2ZkNmUxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA5VDIwNDYwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTEyZDc1N2JmNzg4NGQ0ODcyNTNhOWY2Mzg0ODA2OTJhMjc0Y2RiOTc4OTgyMzM2MWM2Njk4NGY0NjJiMmJjNDYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.N8VIcTIdmyh_IbVjtgY9ndGKF_iPcuCEJzWnrMgeh7U">

太感谢大佬了～(🙏ˊᗜˋ*)
