### ISSUE TITLE
开启插件，图片请求都出现400

### ISSUE THREAD

**Issue by MaxBill** [guqing/plugin-cloudinary#9]
请教下，开启插件后，图片请求都响应400了，设置都是正常的，还需要什么后续处理么
![微信截图_20240523185154](https://github.com/guqing/plugin-cloudinary/assets/16558525/fabeb30c-13dd-4384-a123-247a5d01be16)

**Comment by guqing** [comment]
<img width="240" alt="image" src="https://github.com/guqing/plugin-cloudinary/assets/38999863/c1bfde13-434e-449e-8add-7770d1f2bee7">

你这个图片是什么地址，存储在哪里的，正常情况下是有域名作为前缀的

**Comment by MaxBill** [comment]
这是直接halo的附件管理的地址，没有用图床 ，这种是不是就没法用插件加速了 [手动狗头]

**Comment by guqing** [comment]
> 这是直接halo的附件管理的地址，没有用图床 ，这种是不是就没法用插件加速了 [手动狗头]

我试了本地存储的图片是可以的，并且链接应该是带域名的，比如图片中的 guqing.io， 你检查一下你的外部访问地址配置的是什么怎么会没有域名前缀
<img width="1643" alt="image" src="https://github.com/guqing/plugin-cloudinary/assets/38999863/e5a5dcbe-88e6-4e42-8715-33dd11748f15">

检查你的系统概览中是否有外部访问地址，如果显示未设置之类的则参考文档修改

<img width="566" alt="image" src="https://github.com/guqing/plugin-cloudinary/assets/38999863/ba00732a-2d98-4504-8ccb-6488cda6c497">

**Comment by MaxBill** [comment]
好嘞好嘞，了解了,非常感谢，耽误您的时间了
